[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@pinata/web3"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
